<?php
/*
Name: Wordpress Video Gallery
Plugin URI: http://www.apptha.com/category/extension/Wordpress/Video-Gallery
Description: LanguageXML file for player.
Version: 2.0
Author: Apptha
Author URI: http://www.apptha.com
License: GPL2
*/

ob_clean();
header ("content-type: text/xml");
require_once( dirname(__FILE__) . '/hdflv-config.php');
global $wpdb;
    echo '<?xml version="1.0" encoding="utf-8"?>';
    echo '<language>';
    echo'<play>';
    echo '<![CDATA[Play]]>';
    echo  '</play>';
    echo '<pause>';
    echo '<![CDATA[Pause]]>';
    echo '</pause>';
    echo '<hdison>';
    echo '<![CDATA[HD On]]>';
    echo '</hdison>';
    echo '<hdisoff>';
    echo '<![CDATA[HD Off]]>';
    echo '</hdisoff>';
    echo '<zoom>';
    echo '<![CDATA[Zoom]]>';
    echo '</zoom>';
    echo'<share>';
    echo '<![CDATA[Share]]>';
    echo '</share>';
    echo'<fullscreen>';
    echo '<![CDATA[FullScreen]]>';
    echo '</fullscreen>';
    echo'<relatedvideos>';
    echo '<![CDATA[Related Videos]]>';
    echo '</relatedvideos>';
    echo'<sharetheword>';
    echo '<![CDATA[Share the Word]]>';
    echo '</sharetheword>';
    echo'<sendanemail>';
    echo '<![CDATA[Send E-Mail]]>';
    echo '</sendanemail>';
    echo'<to>';
    echo '<![CDATA[TO]]>';
    echo '</to>';
    echo'<from>';
    echo '<![CDATA[From]]>';
    echo '</from>';
    echo'<note>';
    echo '<![CDATA[Note]]>';
    echo '</note>';
    echo'<send>';
    echo '<![CDATA[Send]]>';
    echo '</send>';
    echo'<copylink>';
    echo '<![CDATA[Copylink]]>';
    echo '</copylink>';
    echo'<copyembed>';
    echo '<![CDATA[Copyembed]]>';
    echo '</copyembed>';
    echo'<facebook>';
    echo '<![CDATA[Facebook]]>';
    echo '</facebook>';
    echo'<reddit>';
    echo '<![CDATA[Reddit]]>';
    echo '</reddit>';
    echo'<friendfeed>';
    echo '<![CDATA[Friendfeed]]>';
    echo '</friendfeed>';
    echo'<slashdot>';
    echo '<![CDATA[Slashdot]]>';
    echo '</slashdot>';
    echo'<delicious>';
    echo '<![CDATA[Delicious]]>';
    echo '</delicious>';
    echo'<myspace>';
    echo '<![CDATA[Myspace]]>';
    echo '</myspace>';
    echo'<wong>';
    echo '<![CDATA[Wong]]>';
    echo '</wong>';
    echo'<digg>';
    echo '<![CDATA[Digg]]>';
    echo '</digg>';
    echo'<blinklist>';
    echo '<![CDATA[Blinklist]]>';
    echo '</blinklist>';
    echo'<bebo>';
    echo '<![CDATA[Bebo]]>';
    echo '</bebo>';
    echo'<fark>';
    echo '<![CDATA[Fark]]>';
    echo '</fark>';
    echo'<tweet>';
    echo '<![CDATA[Tweet]]>';
    echo '</tweet>';
    echo'<furl>';
    echo '<![CDATA[Furl]]>';
    echo '</furl>';
    echo '<adindicator>';
    echo '<![CDATA[Your selection will follow this sponsors message in - seconds]]>';
    echo '</adindicator>';
    echo '<skip>';
    echo '<![CDATA[Skip this Video]]>';
    echo '</skip>';
    echo '<download>';
    echo '<![CDATA[Download this Video]]>';
    echo '</download>';
    echo '<volume>';
    echo '<![CDATA[Volume]]>';
     echo '</volume>';
    echo '<errormessage>';
    echo '<![CDATA[Error Message]]>';
    echo '</errormessage>';
    echo '<buttonname>';
    echo '<![CDATA[Button Name]]>';
    echo '</buttonname>';
    echo '</language>';
exit();
